LOGGING_LEVEL: 'INFO'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

MAX_CHANGES: 50
NCPU: 16
MEMORY_LIMIT: '80Gb'
TREE_DEPTH: 3
MAX_CTR_COMPLEXITY: 4
TREE_LEARNING_RATE: 0.1
LEARNING_BATCH_SIZE: 600000
TOTAL_ESTIMATORS: 5000
VERBOSE_FREQUENCY: 10
ANTIBERTA_CANDIDATES: 50
MIN_DATA_IN_LEAF: 10
